version: "2.4"

x-cs: &cs-common
  build: .
  cpu_shares: 1024
  init: true
  restart: unless-stopped
  environment:
    - POSTGRES_URI=postgresql://postgres:notsecret@pg/cs
    - ADMIN_AUTH=root:root
    - FLAGS_SECRET=123123
    - PGPASSWORD=notsecret
services:
  cs-manager:
    <<: *cs-common
    depends_on:
      - init
    command:
      - /bin/bash
      - -xc
      - >-
        while true; do
          perl script/cs check_db
          if [[ $$? == 0 ]]; then break; fi
          sleep 2
        done &&
        perl script/cs manager
  cs-web:
    <<: *cs-common
    depends_on:
      - init
    ports:
      - 8080:8080
    command:
      - /bin/bash
      - -xc
      - >-
        while true; do
          perl script/cs check_db
          if [[ $$? == 0 ]]; then break; fi
          sleep 2
        done &&
        hypnotoad -f script/cs
  cs-workers:
    <<: *cs-common
    depends_on:
      - init
    scale: 1
    command:
    - /bin/bash
    - -xc
    - >-
      while true; do
        perl script/cs check_db
        if [[ $$? == 0 ]]; then break; fi
        sleep 2
      done &&
      perl script/cs minion worker -q default -j 4
  cs-checkers:
    <<: *cs-common
    depends_on:
      - init
    scale: 1
    command:
    - /bin/bash
    - -xc
    - >-
      while true; do
        perl script/cs check_db
        if [[ $$? == 0 ]]; then break; fi
        sleep 2
      done &&
      perl script/cs minion worker -q checker -j 4
  init:
    <<: *cs-common
    restart: "no"
    depends_on:
      - pg
    command:
      - /bin/bash
      - -xc
      - >-
        while true; do
          perl script/cs check_db
          if [[ $$? == 0 ]]; then break; fi
          perl script/cs init_db
          if [[ $$? == 0 ]]; then break; fi
          sleep 2
        done;
  pg:
    image: postgres
    cpu_shares: 1024
    restart: unless-stopped
    volumes:
      - "cs_pg_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notsecret
      - POSTGRES_DB=cs
    command:
      - -c
      - shared_buffers=256MB
      - -c
      - work_mem=8MB
      - -c
      - max_connections=128

volumes:
  cs_pg_data: